# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Duke Personal Assistant' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Duke Personal Assistant
  pod 'FSCalendar'
  pod 'iOSDropDown'

  target 'Duke Personal AssistantTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Duke Personal AssistantUITests' do
    # Pods for testing
  end

end
